apiVersion: apps/v1
kind: Deployment
metadata:
  name: zen-pg
  labels:
    app: zen-pg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zen-pg
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: zen-pg
    spec:
      containers:
        - name: zen-pg
          image: postgres:14
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: POSTGRES_PASSWORD
          ports:
            - name: zen-pg-5432
              containerPort: 5432
          volumeMounts:
            - name: zen-pg-pv-claim
              readOnly: false
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: zen-pg-pv-claim
          hostPath:
            # https://kubernetes.io/docs/concepts/storage/volumes/#hostpath
            # Linux: /home/username/simplest-k8s/host-mount
            # macOS: /Users/yourusername/path/to/repo/simplest-k8s/host-mount
            # Windows: /Users/username/code/simplest-k8s/host-mount 
            path: /home/z/host-mount
---
apiVersion: v1
kind: Service
metadata:
  name: zen-pg-svc
spec:
  type: NodePort
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: zen-pg