#=================================================
# NOTE: Secrets should not be stored in your repo
# Ensure to base64 encode all values
#=================================================
apiVersion: v1
kind: Secret
metadata:
  name: pg-secret
type: Opaque
stringData:
  POSTGRES_USER: ZenAdmin
  POSTGRES_PASSWORD: temp
  DATABASE_URL: postgresql://ZenAdmin:temp@postgres-svc:5432/zen
---
apiVersion: v1
kind: Secret
metadata:
  name: zen-jwt
type: Opaque
stringData:
  JWT_PRIVATE_KEY: ''
---
apiVersion: v1
kind: Secret
metadata:
  name: zen-google-oauth
type: Opaque
stringData:
  GOOGLE_CLIENT_ID: ''
  GOOGLE_CLIENT_SECRET: ''
---
apiVersion: v1
kind: Secret
metadata:
  name: zen-smtp
type: Opaque
stringData:
  SMTP_SERVER: ''
  SMTP_LOGIN: ''
  SMTP_PASSWORD: ''
  SMTP_FROM_NAME: ''
  SMTP_FROM_EMAIL: ''